---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: webhook
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/webhook
  url: https://github.com/sngular/gitops-helmrepository
