---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: apache-solr
  namespace: flux-system
spec:
  interval: 60m
  url: https://solr.apache.org/charts
--- 
# Keitaro - Consultant
# - CKAN
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: keitaro-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://ot-container-kit.github.io/helm-charts/
--- 
# Opstree Solution Helm Repository
# https://github.com/OT-CONTAINER-KIT/helm-charts/tree/main
# - Redis Operator
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ot-helm
  namespace: flux-system
spec:
  interval: 60m
  url: https://ot-container-kit.github.io/helm-charts/