apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:2J12w5szVeniO/R1DpFA2XxFLyhX/cOOBOxmISsvFTFGT/WGwyCeABAC0BjG99cx4JqSgVBcA8Kv6LwiyaxwQRuWY7P/4m3iGyB1r+zIUBu+LPF1c9W/DsihsqbsuEDqVUkLOkj5E3NFEGv2Dq5SfGVW+x6/mEn5JuaF3Pb8VQ3FA6LcsQm9HFXko//RZg+c6+dim/ohZvUjvU2vKho3FsELmclnVaZqFdsgGI3wdnzqORaHh69TH+gK2XS8qI//nOu+gUa7YbNvYVBkrpQ/YBVFlx9r2+7+rfBWYt6o45sf2ARAqfaGmHlqqVbTMADo69XcxvHdiNUg+arsGTTY/gs7tlCJB2H49rKOBJFbL/uTe81qNuqR689S3iZj9yewggZCOrn3HVEbXlQQbbemrGnZTSlBmhvLxft01IHXt6k45kxML0oie7dGCv0KKADD21NJ9TONOlk0ITJI9qBcubM5oSq0levC1CHsUOOHaN2Z1g7KDsIYOkSVA3YUpnJzBgsteJZ0OKLVHqTu3IJ2uJfa9h4E3Nd3XdsJUlhQ6av7idjGjXYRxgU3C5np2C6L6V0lJK7+tDwfq1oqJC3Sh+19NpssonhfBYNwEjQO+JxxxYVOdZgvE5/DddwuW+MfFzLafQBi9zL1743qMSm5aoDetUxUI8rTwhmbLDir/NJQYKkHEAheEqL18GVk/MA0iiJahlbDSkuZpb+vToTWbolTQ9pkSXigwnGMciSOs6M504DtvImvFFmNZ5uC35qkbzFwbXw4cp8iY1BC7xfMnsSzDnD49J/poNyZjvBgDsOCkFwaHQaHVPyVjxGs8Na2fO9pwDPURlhB8oW8atANn9zIpRYV+LI52YsHc9TG20EmRKtsVT/n4WybyyVWWAgwQPNR7yqeh2hojseuYnzgESZCcH3OfNqUV9KxGBmvUYnvlDJAt/Z2nWmwe6qi/5/ljKoJR+xb7CqyGZbFEu3ZjsFCNKb3Oiu3kBvy5f3WnW6o7FdKMdTxf3eKtF3mkcZE8wkALX3A0yQMObG/3zn+8Du1g+rQqZzPXxaN1NwUlMqvkT7ghGoZCHxqoCsT+NSe6ylkohW3AG2UW5SQS1BCFNdFsa3x+qPqY/WN8p1z5K97jXK783A/oaFw7INVyZXUILhfsebagr/HV6sOflnoOr25ZeKjWf2gA6bzLGGE7gWET5KUQk1VATStFpj6dD+KVoYPWghZbxO2tBWNe/ywzGpqN5gCfUNxkJ6J6cvwQbURtmLGZD2Uy5+ZM3RjcdlDxV2dNzFFijLHtlh/aRSh9Jj1tj9ElULcLTV1wrUAtWENnj23NXUdTHdjVxd5ujmXSrMUiH0LlBlKlPgGwO8XfM7f903/KBWV+sQkeAfheHSfw75ccDLvBZhhSWkgdRQTYPBGu2CD9qmbqzMCXf3CKOvkldE0IpcKbcDQAI6s+9NYSe2VNgnkPiDC2+bCSCz5yrtvGZIamYC7eMozi2KwupyQe9pkVI0g4LlbESz7r9JLZTw0ZO7dhfboYsLWckXK3bDX1PFOnVA9PSPxm4Yx45/uH01YmSAJJys89Yy12WJMhmx32fjVon361nW/M896,iv:VbTt8O4As+qZkR//cenaVPubzzH0NANAq1QoO+XcMck=,tag:6eXo7dZxe7snzk+3+HcpEw==,type:str]
kind: Secret
metadata:
    name: jupyterhub-secret
    namespace: jupyterhub
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-17T16:31:39Z"
    mac: ENC[AES256_GCM,data:mrPlnIjKji7bA2Ryv+to3cXeNl08QKgUBOKaGyNHxIYuZdX8a38FObXekucXAFMnGDXUo6djckK9vwTn/e8pkUQMkkYvE3QLr1fxKjyufX/Yc8MOIfCnDSbLtvJ2MitPwbFXgi5+5gezFzQ/NrwQD90Egdcjp/YBfQWMfE+/mO8=,iv:zlWrC2+W2YV1EU2If4mylccKzZDsEffte80MH5oj6yo=,tag:jc91FwrZFVlXL/Z7w6JwPg==,type:str]
    pgp:
        - created_at: "2023-12-17T16:31:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2+ku1+JwIKZAQ/8DHBE+cLmromNVorZvq4/QLl0oy88YS9guc2YkSAk48p5
            ylGjIBVJM4xTICtTyv6LZ0HfdNwzQmWJQO/DE4xqJXUVXcU7AOA970sjfw2xz8+1
            oUGtPp3uuECG1nPjAWdfCXPbbjHyRTZ2xAOL3rgib/frkKlgcnCDwFfhmoq/SVy1
            PDzaHF5XEFkRH5NHcPgf/eeQOzcL7AayCL7IfenlpGznvFoLn6bM6CUu7/AxSfqm
            pd8NzNiiU1YD0O0lCPdC39zZ1q0I38liWf+Zw33ItmGmCrrWgyCbD7444tXuT6so
            dqjBxFjY79qHzPZP6TH9r4b+sp2EwqFWBNlmor8+RUfkaSQ52cgT1KMGCvDmj8jY
            yqub0M2HjJN6PYmsa7MiKwJBiwLRDap7povj4h8ffIBIhuQbS2TqRmgDSqZfuoBA
            2q1fTlTzjRK25sAUUJJiFmpLH1iA6V885MILRXE1I++YSFtE7guA2t6bcVw4sNkV
            8QkAfEcv4DUHmC8i/l5S9/u27RnV69Km5+apex2Rzz/7lhZrUi3DkdCM5UxplpFX
            nk6+iaNsmtLvU05XiJSP0WuiO54EStbYyhxIsX0Zy67ck2j8HYl+qXL1rj/vVz2X
            ob1zsAKdcfChXfDCD2d1npmi4VKGBP/oVMxNQPjugMsHQbhBblhBcSx5FwCc4IbS
            XgFq51OcjGEQ/B9EUXolgO9vsuTdEe03uTRkUYJj8p2pjPFTdFTDgvgL8VIG4eO2
            EcmwG/6JZukypT8HblUmyzs02ahM2A7NVWLEGIXjKyqHNC8h5husCv8rLD02by0=
            =nD0u
            -----END PGP MESSAGE-----
          fp: A547DF661D5A68E3E9CF7460FA2AF03E06BF9BC1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
