---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ot-helm
        namespace: flux-system
      version: "0.15.11"
  interval: 1m0s
  targetNamespace: redis
  values: ./values.yaml
    
