---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kind-huawei/flux-secrets
  prune: true
