---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: solr-operator
  namespace: operator
spec:
  chart:
    spec:
      chart: solr-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apache-solr
        namespace: flux-system
      version: "0.8.0"
  interval: 1m0s
  targetNamespace: operator
