---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: generic
  namespace: notification-system
spec:
  chart:
    spec:
      chart: charts/webhook
      version: webhook-0.1.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: webhook
        namespace: flux-system
  interval: 1m0s
