---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: generic
  namespace: notification-system
spec:
  chart:
    spec:
      chart: webhook
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sngular
        namespace: flux-system
      version: 0.1.1
  interval: 1m0s
