---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "0.27.0"
  interval: 1m0s
  targetNamespace: vault
  valuesFrom:
  - kind: ConfigMap
    name: vault-values
    valuesKey: values.yaml
    optional: false
