---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 1password
  namespace: flux-system
spec:
  interval: 60m
  url: https://1password.github.io/connect-helm-charts
---