apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:aoxTBwDZIFxQLCc7zzJ3YQDgK8ilivMnem7WovajFREGACqXvt+Rb37Q7zcKU+El0yi4/BNGiBwFJOhFRKjXnhFwd2vKql5pu6rotNvva76AEDi1McVdo6cgGZ0ToG05nxYo444DLmI1fSCxGhwqiER8NuxGfJWjMx85ZNGWxj5fDEtkeqq2h0Gz+QDqaguAgkWiAmUQoSIV3ZdpewXLH7dfPaYExF9xru/ctPrz2ozuBVDmkZ5oPgj3jLM8zc/SUJyIE6EeADTCnAtjFDz4OWLeH7B96lcL4onNHzBxXooCn7NQq/rzP0+XRNU4WIOEvs8wvw2tAgVZj/lepsuduqV6RoA=,iv:OugJltyJy5JhbUHJWmLP2WNJOVOtG2EZFfFnGWZ0XUI=,tag:Xge+OP23LPdQHyu83Zs+1Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: jupyterhub-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T09:04:54Z"
    mac: ENC[AES256_GCM,data:Gw91dI4FTkTbbSXXtb8CeT78SoHDWCdvvgxDBbP5iovwSdrlU0DqmDVsDPWSqMbjVFMHdh4T8ZoyCQMVzlnqQiXPZRgEY3S3kXr0KMxT2izMIqrjEmT2GAn6Ug1IkM2N50ZMOWAN614nKoWMBehAE1KaU8DeMpM8s9H2sytIge4=,iv:+IVlU9hcsTJNHa+uTKPhd7Xfshhjt0RHKyaJur5bB1E=,tag:2fb9ep4sJr1nF+ZM8X/Zog==,type:str]
    pgp:
        - created_at: "2023-12-13T09:04:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2+ku1+JwIKZAQ/+KC111sZ+YLawnUfvZaKYQkUYlRbwzQggyPuyDQ6g3MyB
            kuAWLw0dUv0of+NiYRJWa0HcECLtm20LWz//Il2KMfvuMNQLNcZN8NlqtD55yhs2
            dJnoK36y9ub0Vc4b1XerpTqdozlrvG/Ljzc5MMDx68ngM+3NtHh/UxljZR6HE/uA
            AIXc6GO8ZHMqVGS6UmxP3R20LKD6BUDIJw/IFOwjrF5Bxfpy6ew/9GW6dKgrRBy8
            tpJH7hrXXeikz1gU9QrzKj60um18z05TzCLG0lphNNGIA9qiraPrpMjGqRSTa536
            anff8frbV7q7YvJP8RoaVgmhUclb/PN4YqJDI9xtUSrO0+PzPGWRTYMAPSiHaEOq
            kdMNtDcpxtdA+hkOFgA+SwSIz5l4mGReiXAm90ojWvJc2zMLC1djlJRdftBBZEZu
            9IfqT/EHe7LeWZWg5Q5BmrfBFGEs6TL8HdXNCGZqe3QHd5zm9p6/8vaEV5Jm7daC
            zPg6WfQfYipYl1k36UIfPTI5mQIwCT2WMLJeHsjF+P9lPoglXqSK4cKeEFoqCAGE
            7e73E6DJrPn8lKU+/1Sxq7QJEv5tj9AB7tuWmsDb1XYw8WF2kvNr+er5Rc2zCBM3
            F2h4hj9c2D9UaDq3z/3uce8Pjncf8ub5QtF4wWRkvTG1qxE0sdGyrEv04jhAqDvU
            aAEJAhAvVBTrVE539OXzUFvlQ02du+SbDY/Wc42bntB28nP9W96rUbt2TyaTvhGU
            66iorZ8xIF+Jpiebf5ueHWG9pVNpm4VtLc4NG1BtiTMfIxpzmOFW2wTKYVWVS4ho
            OTsjg9/ohEaG
            =jv7w
            -----END PGP MESSAGE-----
          fp: A547DF661D5A68E3E9CF7460FA2AF03E06BF9BC1
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
