---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chart:
    spec:
      chart: jupyterhub
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: flux-system
      version: "3.2.1"
  interval: 1m0s
  targetNamespace: jupyterhub
  valuesFrom:
    - kind: ConfigMap
      name: "jupyterhub-values"
      valuesKey: values.yaml
