apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:dPp1hG+iVdaQ5Arvxk0ddD79lu272slY03kcw3SYdv3ULvIq9R0Cu+LYi52kmJEc4PtKmtTW7GAzDuj18YnUBP/E/WK2Ca5wCCHQvK5AiQAHldirlusQIYtacPTbrQgi8Fi59ldwyUT849r7wx1ddB0tqhSmYF0Qu+l2p8UIUWYUy99Tltd/prUG1mWaEOQW3ymla9UHqL+vZ6RKOef3QdYOVDKtZwwn+SPoKWlmAaDtfVfHMDTosK/koclrdg4WBiXCvjlw/GCx0MfSKEe9Ao8ADd0pk07Fhnhei4VeIBOFCVQl1tQPaJCKKFEvjtYV1S8SlewyU3x5EHkeIv4yxceDLQziNAWK4oEixVFuB8wNd1jeBydBk30AqSufwzPj6HZQSp9O583dFOdQpl+X2k/vHCH1KtZlpuKkfUkklMskh6k2J4xGi+23nvS+/UiPGjp+yZKLoKkZRhgkDIDlxRqjZnE4mpKKP3gYRe/9aiLVj0fesA1X8e2P/vGxxqcM07vg2cEO4wAI7rssq1GpNUR6tfFmfTZTWB+fv8HgbgFzlXcIB5ZzwtYw8B4OlecCYCO/Jz0LQzjdzko+1iNQn6YmhGBYoEcqaFELUcZxKCeiP5rGxvPYPzL3UxKLKAzHEN3lM5cf6OeTIZwLWAkqsDecmPfLkxQ4MT0P52avhQGR4x4emxsp9rkDvHidd4BSNg4d8fDXUMNxnI7qQ3p/X9GlzHGj9XXSDNSbEdEr5QxQmUmlxLlx/KAoze/OgEOEUr5t7+s0rXrxbbEb5lwO1TwxlqgchxWy7BOgJhwHlWoDixj+sdu6zRCdq+DIRaPE/iqsSSbz0RDOZ44SsQvav3GVwuMwGk6A8+e9weJW5Zny4TQLUXCQvJvPV/WEiiQMhbggf5eWPn9liuDdMrRsNO65kpi3Ed2CTD/NQGNsrnZk+yITYrgo4I345ZAFT9WZN1FPLbfBvwAAyoMq6HRj4RFc19erWriAiyq//8jqOdhfWCMkk18RFtPRQL+4zygWzmR9NSv2qw584E1s+zFTcw61UADV20WCyLrBb971K6voGKN4q5e/TyBRcnHU9LTQDDq5CTQJYXJOnqVwd6vJljBKfTVwEGqB6AwTHng3xXX+3njLDPlZXgj4CIJmknLONKjRlC2XOD3B+zoY465WFdV/EGPp/m+SPiUlexEkTOH8HsHm3LzvJ6RHmomng+GxrQyfIQj2oA9BlqzD+xyI37BRUesZVBmpqwbDFQ==,iv:5qu17YsASxkiUOneS3EIqjXN7l3MMGFVjAwCSa/Gt7w=,tag:NxUMzKggctheddTs7yDPEg==,type:str]
kind: Secret
metadata:
    name: jupyterhub-secret
    namespace: jupyterhub
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T09:59:33Z"
    mac: ENC[AES256_GCM,data:4MmOXbKgmNkZGKsT3xpGsUy0TRqr+csX3si33IRiUQQonOD5mDRfFM6P7UMt2ujCht8YR/cS+EAGTOygwB4bLI2yE37EjGoVLDGqxDwSkUEP2hZrOUOkWoHqHL0tZuI05yse8Ecs2rSmURV8lpL3mhWSzHteSWvVXF3xiBlcZMw=,iv:sCQPt0uJKucUqdaOilgumJaAwqLrujwiNLC60LSXkZk=,tag:4L+JJZShWosvSHTXPB6PYA==,type:str]
    pgp:
        - created_at: "2023-12-13T09:59:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2+ku1+JwIKZAQ/+Jlt1dGqxL5PBLIk3eafpR9roXFyC4HB1imgUW/TQmmgL
            fc4Dg7SpiYHCLt9T+t8of9D0Aiit7bNKlR5qJ8fXvAKH6jIyEogB2EDQHOo9Ci3e
            15oEqZ2s1cB6Fr3c83tWnN6qF39/Q95teTEw9HZVR4IF/pL1pP7rmencVrMDEZiA
            OAm+I6XIaK5NDGKd40KztA7a3IRyBx7bR/jJi9zEdVVKV/FetgeN5Oc7IAVucMjz
            IDLKC3TZ/N4wfPJIS6g4+nu13Ir94NlJuyfCxj0l7qDxcak7tTgZSZXdhbszM5l9
            KCQOtbpFu9AvMDEcYi/ve+lzKfOpMqJ5KJt4p6dQujMY0MShJruaYM73dJcA6PMx
            hFa88ePpMrkLTNtJ7JCT18ZsGIKiru/vhovpEv//mT1HKZuahIy9+4TxWxAuACNA
            N7GSpXWQApMV3OZVJEJSypTn7isRGwK7MX3yFY1L3UbA5cOx9AbkPbze4GBrgX/s
            aWm5lYT9JjW+nJm6HoUJG4mOr/T60EL22Ol1dW5R3pYO8YM5u66cKRrt6VMsZ6Sm
            cXI0w9tY1MOSXxr7/iL7Z7oRBO7Ez0XBKav5oZ/FOZaoWOWybeJY78+qMEx2prRN
            0mAgc07JdgRBb6qqIzGMbXrz5q3nwxlk6MH+x9DjD6koAs4fHjFIdg+cUWT09jPU
            ZgEJAhDL57qyUgvrnLpib2IvM4HifRu6PxiFAw7zSAhJbtlrMNXtk8A1uFmKgft3
            frZcsF9IEKB8XGXAA6PYNlrYFNFnTNtlnZcb0u+XGi30bsvrdJc1+cGLcukY8IlL
            o2cW8TCycw==
            =Xb6B
            -----END PGP MESSAGE-----
          fp: A547DF661D5A68E3E9CF7460FA2AF03E06BF9BC1
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
