# Redis Operator
# see: https://ot-redis-operator.netlify.app/docs/installation/installation/
# 
# Redis Operator is developed as CRD(Custom Resource Definition)
#  to deploy and manage Redis in standalone/cluster mode. So CRD 
# is an amazing feature of Kubernetes which allows us to create 
# our own resources and APIs in Kubernetes. For further information 
# about CRD, please go through the official documentation:
# https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/
# 
# There are four different Objects available under redis.redis.opstreelabs.in/v1beta1: 
#  - Redis
#  - Redis Cluster
#  - Redis Replication
#  - Redis Sentinel
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: operator
spec:
  chart:
    spec:
      chart: redis-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ot-helm
        namespace: flux-system
      version: "0.15.9"
  interval: 1m0s
  targetNamespace: operator
  values: ./values.yaml
