---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  interval: 60m
  url: https://hub.jupyter.org/helm-chart/
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 60m
  url: https://helm.releases.hashicorp.com
---
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 1password
  namespace: flux-system
spec:
  interval: 60m
  url: https://1password.github.io/connect-helm-charts
---

