---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: generic
  namespace: gitops-series
spec:
  address: http://generic-webhook.notification-system/webhook
  type: generic
