apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1password-deployment-demo
  namespace: 1password-demo
  annotations:
    operator.1password.io/item-path: "vaults/kind-win/items/demo"
    operator.1password.io/item-name: "1password-deployment-demo"
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1password-deployment-demo
  template:
    metadata:
      labels:
        app: 1password-deployment-demo
    spec:
      containers:
      - name: 1password-deployment-demo
        image: ruslanguns/go-backend:latest
        resources:
          limits:
            cpu: "0.1"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "32Mi"
        envFrom:
        - secretRef:
            name: 1password-deployment-demo
