apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: 1password
data:
    token: ENC[AES256_GCM,data:aI5lBhpSfR/4t3X/hFl3BJBhDlQTeuKfKg0wUDrR2du6kBD5NTN4r7BijjEYUrnpRSG4ppCwR0p5rlSGBxWj0Fwc7HrZ4CKPIiv9CS57/tGkJM5YV+mJhWuxA5MWJzqA9cpBPDI+eA6FjjQg6ElC2bMOFVoJr6h/DE7UhKD9W9V+p7zvcijc+5Q/nSS8GlxwJrb5JW4G3IVOtQ+3GOUCFwA+BG71gETn1hkdCiOhaJ0D2fC43HEPSmcznBXlOrKPttMBTm9HwFlXNOopWV8ezQnzYXw9xQ1x0vP0k62ou+bsAiJdEMEe8DNgvcMmm9ut5VA7xJF0ZZxZ61+lKHEJbtNMhQLSKMy56H2UjlLORFHeEIjzpPswCyPd0BQi02B1WgJIJ4HtWJO64pszf2+E11SOem799mX6nix/XOwguaNDyRWUQ2KBRmoK0WwJ/Sb8dPXfE3maZn2V4xY+XGZRup5NaKEp4SFZ1QvzBAuDgnJyJDeIERuMp+YwptrBUsNWd2w65P1s9E0Jx3ZAQ0tMwMEuQ4FnjpfKWMVd3VTh+cHdJOHWwsoizxL1RzWtclbo6rvbDMPxldUrl4NtEgcCeZixIB8wRaoIyS1Z+hFl09IlwVGLe4ofJX2XysSjndaSCP8y+Xr7aoiMv+ey/uRB7cfbrBGUzaVVC2TP3+IWJGP6Nec22Ii2fHVlJsSA/veKfDenX4AqFbutpJ135Ey09mApCpWA2V+GMM3FkoDLXdNHgU5fm7BW1KsQzSIYUE30dE6xAheTRBFcIKw6LQUsRtDWBg8ZcItgzPVXGy5qT721pjllejsWKq7I5SAh1F24/eYM+QcQwmdk0RjAKTt/yp6w+r7KrzbHB8KWR4QgpElU7RGFKJ9DYc3hTIeU6iPR3BLy6Fs53z0KzJR3nKFKnxHMjdDWcvo1VTngETBbjjbu529R6DvDStQdsjz5rjngZVxzXXDvEglmVMQeBC6Aqjdm3UpIdTzjKeqBYPrARcmsLZfvUmzccb/2dd7T8eZCrOZlNaTPZMQqhS2K7B1OkadXTW25wm69/Owt485WFSPeRLset9k4mWSG8vXTGBVYhZWQ1lAGJanfIZOYIQ/e5ZDgiuHUU/uRmSaQFGG5hb9h3KckVUID8g==,iv:wJoYGIb6+t+jBkuh62ls5Ibgeo/0xPK5TjrlLbrSJHE=,tag:lguSEHR3spUkPKWHAtfqRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-15T12:17:57Z"
    mac: ENC[AES256_GCM,data:FMX8Nf7VxgukZS8RaliCioNXFKW3VL5Xt7irj/QomY/DisEBVzPCmvG0EsWpitmjvND1IyZlhOkJmqulMEWEJbmCZuVZy3fDEHBVWv2IRZdcTdN/DXf2F9q2raoKCecstlbvFonFjJpEiyK4IrCp+USqSQZ2tz2OvQzwP7Qd82c=,iv:nIM9cUp2QylJnHeVywJ4vE5/v7R/5vd7jgPbV4a9ME0=,tag:jvO54l0eMfhLlRar+RlEyg==,type:str]
    pgp:
        - created_at: "2023-12-15T12:17:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2+ku1+JwIKZARAAi76z0gSpit/rrWKYRKLi8eTmImvi7Jmg9H3RTFi5/8EB
            lHwyDknj3C02TF9b39gp7RBKgR0zFaaBuF9rKsXzYd5Cwvd75uBWYQp3H2ipM2o4
            7PkwwUmTIx9xhrV5s9MefREgJluJD7vcG8sfLM7TuJmw6oRybg4QSC9eWDwddNKq
            yNGz5MDMRn21iM0fU4IUK9BReqddU0xxCLhYnU/gxrQv582Uc9bc9Hqx8lBA9ZLx
            N29hCxtwOeCqDvtb/NJzBo20njcwML6sAtSOcftbKDhzCib7RgC3oQahfsvOM/LJ
            jntv4dBlZ+ZO3AyjH06ySzT8UWbQ4dGyQqb+5gpPhy8c978n1yJ+2fyKbnw3SdNX
            o693oXon1oEzqGU5y6Mr9WomFPrnfEv6rb2IrYWeNyGRrwTWzrjFKpP4XapPosEC
            7mirUJD13V/W8x1nbEfbk/vNMOf+okCwXGl2+DMKE+T6H7hNzmu/zpWsPdByYT0N
            3BhofMUXX3FKDz4hSyhJNQEJplad3rRkGiOVmKet3paxFiVwZ7HVAXjPEW1AWXKS
            tZxUinwnboVe/sxLMSMdK6y3kGh2v2Hoq1RdxJvUbTTJ5KpKUQ3Ipsg4rKpIbW6A
            6wcyKu4LzDVFY4yjeBjOV7ckNtBZv9/Hlk+IiEY8dLqHNtrUJ89RB+ZOklnwzW/S
            XAGipxV7dNzkSFYNE0/R0UmCl78aRD4+0DEzbA37te698RLfLoVu0hn5oUSdtrNb
            oGtA68CQJnkq5fNnlyQH0SDjv6K/CWixP3a2qBhOfoM0VnwkSHWvq4bM01qL
            =pzvO
            -----END PGP MESSAGE-----
          fp: A547DF661D5A68E3E9CF7460FA2AF03E06BF9BC1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
